version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito_parser
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parser_service:
    build: ./parserService/
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: avito_parser
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - db
  bot_handle_service:
    build: ./BotService/
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: avito_parser
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - parser_service

volumes:
  postgres_data: 