from datetime import datetime, timezone
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import LoginToken, User
from app.schemas import AuthToken, LoginRequest, TelegramTokenLoginRequest
from app.security import create_access_token, hash_secret, verify_password

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post(
    "/login",
    response_model=AuthToken,
    summary="Log in with email and password",
    description=(
        "Authenticates an existing website user by verified login email and password. "
        "This endpoint does not register new users: the first account entry point is Telegram. "
        "Returns a JWT access token for website requests."
    ),
    response_description="JWT access token and current user profile.",
)
async def login(payload: LoginRequest, db: Annotated[AsyncSession, Depends(get_db)]) -> AuthToken:
    result = await db.execute(select(User).where(User.login_email == payload.email.lower()))
    user = result.scalar_one_or_none()
    if not user or not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid email or password")
    if user.status == "banned":
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="User is banned")
    if user.status == "deleted":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")

    return AuthToken(access_token=create_access_token(user.id, user.user_role), user=user)


@router.post(
    "/telegram-token",
    response_model=AuthToken,
    summary="Exchange Telegram one-time token for JWT",
    description=(
        "Used by the website after a user opens a login link generated by the Telegram bot. "
        "The raw one-time token is checked against its stored hash, must be unused and not expired, "
        "then it is marked as used. The response is the normal website JWT."
    ),
    response_description="JWT access token and current user profile.",
)
async def login_with_telegram_token(
    payload: TelegramTokenLoginRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> AuthToken:
    token_hash = hash_secret(payload.token)
    token = await db.get(LoginToken, token_hash)
    now = datetime.now(timezone.utc)

    if not token or token.purpose != "telegram_site_login" or token.used_at or token.expires_at <= now:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid or expired login token")

    user = await db.get(User, token.user_id)
    if not user or user.status == "deleted":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")
    if user.status == "banned":
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="User is banned")

    token.used_at = now
    await db.commit()
    return AuthToken(access_token=create_access_token(user.id, user.user_role), user=user)
